### ISSUE TITLE
Add Query to get all users

### ISSUE THREAD

**Issue by bleakney** [bleakney/free-maps#22]
**In TypeDefs.js:**
users: [User]

**In resolvers.js**
 users: async () => {
      return User.find()
        .select("-__v -password")
        .populate("savedItems")
        .populate("postedItems");
    }

**test before pushing to github by adding a few new users in graphql playground with below mutation, then running the getAllUsers query in the graphql playground**

mutation addUser($email: String!, $username: String!, $password: String!) {
  addUser(email: $email, username: $username, password: $password) {
    token
    user {
      _id
      username
      email
    }
  }
}

in "VARIABLES" section of the playground just put this in, rinse and repeat with a few other mock data options and then run:

{
  "email": "email@email.com",
  "username": "testuser",
  "password": "password123"
}

**if you need help figuring out how to run the getAllUsers query once you've written the typedef and resolver, just hit me up on slack 😄 **

**Comment by Mindydiane** [comment]
:)
